// Message for http error response
exports.ERROR_MESSAGES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  INTERNAL_SERVER: 'INTERNAL SERVER ERROR',
  API_NOT_FOUND: 'API NOT FOUND',
  BAD_REQUEST: 'BAD REQUEST',
  FORBIDDEN: 'FORBIDDEN',
  ADD_TO_CART: 'QUANTITY IS NOT ENOUGH',
  UPDATE_ERR: 'UPDATE ERROR',
  DATA_INVALID: 'DATA INVALID',
  DATA_NOT_FOUND: 'DATA NOT FOUND',
  ADDRESS_INVAID: 'ADDRESS INVALID',
  UPDATE_USERNAME: 'UNABLE TO UPDATE USERNAME',
  UPDATE_EMAIl: 'EMAIL ALREADY EXITS',
  DATA_DUPLICATE: 'DATA DUPLICATE',
};
